services:
  client:
    image: yannvillellas/polito-se2-24-20-kiruna-explorer-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map Vite's default port to host machine
    environment:
      CHOKIDAR_USEPOLLING: "true" # Enable hot reload in Docker

  server:
    image: yannvillellas/polito-se2-24-20-kiruna-explorer-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Map backend port to host machine
    volumes:
      - ./server/src/database:/usr/src/app/src/database # Persist SQLite database
    environment:
      NODE_ENV: production
      DB_PATH: /usr/src/app/src/database/database.db
