services:
  client:
    image: yannvillellas/polito-se2-24-20-kiruna-explorer:client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  server:
    image: yannvillellas/polito-se2-24-20-kiruna-explorer:server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/src/database:/usr/src/app/src/database
    environment:
      NODE_ENV: production
      DB_PATH: /usr/src/app/src/database/database.db
